version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
  node:
      image: "node"
      user: "node"
      working_dir: /home/node/app
      container_name: nodejs
      environment:
        - NODE_ENV=dev
      volumes:
        - ./nodejs:/home/node/app
      expose:
        - "3000"
      ports:
        - "3000:3000"
      #command: "npm start"
      command: tail -F anything
      links:
        - mongodb
  mongodb:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - ./mongodb:/data/db
      # environment:
      #     MONGO_INITDB_ROOT_USERNAME: root
      #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
  mongo-express:
    image: mongo-express
    ports:
      - 8084:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      #ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
# check log in mongo-express container : config.js warning ! (admin:pass)