version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8080:8080
      depends_on:
        - postgres
  node:
      image: "node"
      user: "node"
      working_dir: /home/node/app
      container_name: nodejs
      environment:
        - NODE_ENV=dev
      volumes:
        - ./nodejs:/home/node/app
      expose:
        - "3000"
      ports:
        - "3000:3000"
      command: tail -F anything
      #command: node app.js
      links:
        - mongodb
  mongodb:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - ./mongodb:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
  react:
      image: "node"
      user: "node"
      working_dir: /home/node/app/react-front
      container_name: react
      environment:
        - NODE_ENV=dev
      volumes:
        - ./react:/home/node/app
      expose:
        - "4000"
      ports:
        - 4000:3000
      command: tail -F anything
      #command: npm run dev